name: GLaDOS Auto Checkin

on:
  schedule:
    - cron: '20 5 * * *' # 每天 0 点运行

jobs:
  checkin:
    runs-on: ubuntu-latest # 运行环境
    env:
        TOKEN: ${{ secrets.DING_TOKEN }} # 传递 token
        COOKIE: ${{ secrets.GLADOS_COOKIE }} # 传递 cookie
        USER_AGENT : ${{ secrets.USER_AGENT }} # 传递 USER_AGENT
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # 获取仓库代码
      - name: Set up Python
        uses: actions/setup-python@v2 # 设置 Python 版本
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip # 更新 pip
          pip install requests # 安装 requests 库
      - name: Run script
        run: python auto_card.py # 运行脚本
